<a href="https://colab.research.google.com/github/shahalam1111/GenAI/blob/main/Text_Representation_Word_Embeddings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"text":["people watch shahalam",
                           "shahalam watch shahalam",
                           "people write comment",
                           "shahalam write comment"],"output":[1,1,0,0]})

In [3]:
df

text  output
0    people watch shahalam       1
1  shahalam watch shahalam       1
2     people write comment       0
3   shahalam write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df["text"])

In [6]:
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'shahalam': 2, 'write': 4, 'comment': 0}


In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 0, 2, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1]])

In [8]:
cv.transform(["Bappy watch dswithbappy"]).toarray()

array([[0, 0, 0, 1, 0]])

In [9]:
X = bow.toarray()
y = df["output"]

# N-grams

In [10]:
cv = CountVectorizer(ngram_range=(2,2))

In [11]:
bow = cv.fit_transform(df["text"])

In [12]:
print(cv.vocabulary_)

{'people watch': 0, 'watch shahalam': 4, 'shahalam watch': 2, 'people write': 1, 'write comment': 5, 'shahalam write': 3}


# TF-IDF (Term frequency- Inverse document frequency)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [14]:
arr = tfid.fit_transform(df["text"]).toarray()

In [15]:
arr

array([[0.        , 0.61366674, 0.49681612, 0.61366674, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.52546357, 0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.61366674]])